---
- hosts: all
  tasks:
  - name: "Start cadvisor container"
    docker:
      name: cadvisor
      image: google/cadvisor
      state: started
      expose:
      - 8080
      ports:
      - 8080:8080
      volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      restart_policy: always
