---
- hosts: all
  tasks:
  - name: "Update Apt"
    apt:
      update_cache: yes
    become: yes
  - name: "Install prerequisits"
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python
        - python-pip
        - python3-pip
    become: yes
  - name: "Add Docker signing key"
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    become: yes
  - name: "Add Docker Repository"
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
    become: yes
  - name: "Update Apt"
    apt:
      update_cache: yes
    become: yes
  - name: "Install docker-ce"
    apt:
      name: docker-ce
      state: present
    become: yes
  - name: "Install docker-py"
    pip:
      name: docker-py
    become: yes
  - name: "Download docker-compose"
    get_url:
      url: "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86_64"
      dest: /usr/local/bin/docker-compose
    become: yes
  - name: "Make docker-compose executable"
    file:
      path: /usr/local/bin/docker-compose
      mode: 'a+x'
    become: yes